Comparacion/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/redirect', 'SocialAuthFacebookController@redirect');
Route::get('/callback', 'SocialAuthFacebookController@callback');





Route::resource('tienda','tienda');





Route::get('articulo','articulo@buscar');


Route::get('Tienda','tienda@indexs');




Route::resource('Articulo','Articulo');




Route::get('buscar', 'Comparar@vista')->name('buscar');


Route::get('mostarArticulo', 'Comparar@index')->name('mmostarArticulo');





Route::resource('Comparar','Comparar');

Comparacion/app/Http/Controllers/Comparar.php
<?php

namespace App\Http\Controllers;



use Illuminate\Http\Request;
use App\Articulos;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;

class Comparar extends Controller
{


	     public function store(Request $request)
    {

       $clave=$request->categoria;




   			$Articulos = Articulos::all();


 		return view('comparar.index',compact('Articulos','clave'))

            ->with('i', (request()->input('page', 1) - 1) * 5);

   

    }


    	     public function vista()
    {
       





        return view('comparar.buscarArticulo');

         

    }
   
}

Comparacion/resources/views/comparar/buscarArticulo.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Buscar</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('Comparar.store') }}">

                      


                        {{ csrf_field() }}






                        <div class="form-group{{ $errors->has('provincia') ? ' has-error' : '' }}">
                            <label for="categoría" class="col-md-4 control-label">Categoría de Producto</label>

                            <div class="col-md-6">
                                

                            <select name="categoria" class="form-control" >
  <option value="Computadora">Computadora</option>
  <option value="lavadora">lavadora</option>
  <option value="Impresora">Impresora</option>
<option value="Pantalla">Pantalla</option>
  <option value="Maquina de cafe">Maquina de cafe</option>
    <option value="Celular">Celular</option>
      <option value="Radio">Radio</option>
</select>

                            </div>
                        </div>







                                <button type="submit" class="btn btn-primary">
                                    Buscar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Comparacion/resources/views/comparar/index.blade.php
@extends('layouts.master')
@section('content')

<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Articulos</h2>
            </div>
            <div class="pull-right">
                
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        
    @endif

    <table class="table table-bordered">
        <tr>
          <th>No</th>
            <th>Nombre_articulo</th>
            <th>categoria</th>
            <th>precio</th>
            
            <th>nombre tienda</th>
            <th>imagen</th>
     </tr>
         @foreach ($Articulos as $Articulo)

        @if($Articulo->categoria===$clave)

    <tr>
       <td>{{ ++$i }}</td>
        <td>{{ $Articulo->nombre_articulo}}</td>
        <td>{{ $Articulo->categoria}}</td>
        <td>{{ $Articulo->precio}}</td>
      

        <td>{{ $Articulo->id_Tienda}}</td>

<?php
//aquí coges de donde sea la ruta que quieres mostrar
$ruta=$Articulo->imagen;

?>



        <td><img src="<?php echo $ruta; ?>" width='238' height='100'>  
       </td>




       
    </tr>

   @endif


    @endforeach
    </table>

 
@endsection