Comparacion/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/redirect', 'SocialAuthFacebookController@redirect');
Route::get('/callback', 'SocialAuthFacebookController@callback');





Route::resource('tienda','tienda');





Route::get('articulo','articulo@buscar');


Route::get('Tienda','tienda@indexs');




Route::resource('Articulo','Articulo');




Route::get('buscar', 'Comparar@vista')->name('buscar');


Route::get('mostarArticulo', 'Comparar@index')->name('mmostarArticulo');





Route::resource('Comparar','Comparar');

Comparacion/app/tiendas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class tiendas extends Model
{
    

protected $fillable = [
        'nombre', 'codigo','ubicacion'
    ];
    
     public function user()
    {
        return $this->belongsTo('App\User');
    }


     }

Comparacion/app/Http/Controllers/tienda.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\tiendas;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Validator;


class tienda extends Controller
{


    public function __construct()
    {
        $this->middleware('auth');

      ///  $this->middleware('admin');

    }

     public function index()
    {
        $tiendas = tiendas::paginate(5);




        return view('tiendas.index',compact('tiendas'))
            ->with('i', (request()->input('page', 1) - 1) * 5);

    }
      public function indexs()
    {
        $tiendas = tiendas::paginate(5);


        return view('tienda',compact('tiendas'))
            ->with('i', (request()->input('page', 1) - 1) * 5);

    }


        public function create()
    {
        return view('tiendas.create');

    }
    public function store(Request $request)
    {

$this->validate($request, [
            'nombre' => 'required',
            'codigo' => 'required',
            'ubicacion' => 'required',
            
        ]);

        tiendas::create($request->all());


        return redirect()->route('tienda.index')
                        ->with('success','tienda creada correctamente');
    }
    public function show($id)
    {

        $tiendas = tiendas::find($id);
        
        return view('tiendas.show',compact('tiendas'));
    }

 public function edit($id)
    {
        $tiendas = tiendas::find($id);
        return view('tiendas.edit',compact('tiendas'));    
    }
       public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nombre' => 'required',
            'codigo' => 'required',
            'ubicacion' => 'required',
            
         
        ]);

        tiendas::find($id)->update($request->all());
        return redirect()->route('tienda.index')
                        ->with('success','tienda actualizada correctamente');
    }

       public function destroy($id)
    {
        tiendas::find($id)->delete();
        return redirect()->route('tienda.index')
                        ->with('success','tienda eliminada correctamente');
    }
    






    
}

Comparacion/resources/views/tiendas/create.blade.php
@extends('layouts.master')

@section('content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Crear tienda</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('tienda.index') }}"> Volver</a>
            </div>
        </div>
    </div>
   
    {!! Form::open(array('route' => 'tienda.store','method'=>'POST')) !!}
         @include('tiendas.form')
    {!! Form::close() !!}
@endsection

Comparacion/resources/views/tiendas/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Cuenta</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('tienda.index') }}">Volver</a>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    {!! Form::model($tiendas, ['method' => 'PATCH','route' => ['tienda.update', $tiendas->id]]) !!}
        @include('tiendas.form')
    {!! Form::close() !!}

@endsection

Comparacion/resources/views/tiendas/form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Nombre:</strong>
            {!! Form::text('nombre', null, array('placeholder' => 'Nombre','class' => 'form-control')) !!}
            @if ($errors->has('nombre'))
                <span class="help-block">
                    <strong>{{ $errors->first('nombre') }}</strong>
                </span>
            @endif
        </div>
    </div>
















    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>codigo:</strong>
            {!! Form::text('codigo', null, array('placeholder' => 'codigo','class' => 'form-control')) !!}
            @if ($errors->has('simbolo'))
                <span class="help-block">
                    <strong>{{ $errors->first('codigo') }}</strong>
                </span>
            @endif
        </div>
    </div>

    
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>ubicacion:</strong>
            {!! Form::text('ubicacion', null, array('placeholder' => 'ubicacion','class' => 'form-control')) !!}
            @if ($errors->has('descripcion'))
                <span class="help-block">
                    <strong>{{ $errors->first('ubicacion') }}</strong>
                </span>
            @endif
        </div>
    </div>



   
    {!! Form::hidden('user_id', Auth::id() )!!}
    
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Guardar</button>
    </div>
</div>

Comparacion/resources/views/tiendas/index.blade.php
@extends('layouts.master')
@section('content')

<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Tiendas</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('tienda.create') }}">Crear una tienda</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Nombre</th>
            <th>codigo</th>
            <th>ubicacion</th>
            
            <th width="280px">Action</th>
        </tr>
            @foreach ($tiendas as $tienda)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $tienda->nombre}}</td>
        <td>{{ $tienda->codigo}}</td>
        <td>{{ $tienda->ubicacion}}</td>
       
       
        <td>
         <a class="btn btn-info" href="{{ route('tienda.show',$tienda->id) }}">Consultar</a>
            <a class="btn btn-primary" href="{{ route('tienda.edit',$tienda->id) }}">Editar</a>
            {!! Form::open(['method' => 'DELETE','route' => ['tienda.destroy', $tienda->id],'style'=>'display:inline']) !!}
            {!! Form::submit('Eliminar', ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
        </td>
    </tr>
    @endforeach
    </table>

 {!! $tiendas->links() !!}
 
@endsection

Comparacion/resources/views/tiendas/show.blade.php
@extends('layouts.master')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Tienda</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('tienda.index') }}">Volver</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>tienda:</strong>
                @php
                   echo $tiendas['nombre'] . ' ('. $tiendas['codigo'] .')';
                @endphp
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre :</strong>
                {{ $tiendas->nombre}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>codigo:</strong>
                {{ $tiendas->codigo}}
            </div>
        </div>

           <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Ubicacion:</strong>
                {{ $tiendas->ubicacion}}
            </div>
        </div>
          
    </div>
@endsection